#!/bin/sh

# get added and modified python files
for file in $(git diff --cached --name-only --diff-filter=AM | grep -E '\.(py)$')  

# run black
do    
	black "$file"
	
	$(git add "$file")    
	
	done


